apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limits
  namespace: trainxops
spec:
  limits:
  - max:
      cpu: "1"
      memory: "1Gi"
    min:
      cpu: "200m"
      memory: "256Mi"
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "300m"
      memory: "300Mi"
    maxLimitRequestRatio:
      cpu: "2"
      memory: "2"
    type: Container