apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-container-pod
  name: multi-container-pod
spec:
  containers:
  - image: nginx
    name: webserver
    resources: {}
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx
  - name: log-reader
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "tail -f /var/log/nginx/error.log"]
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx
  volumes:
  - name: nginx-logs
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
