apiVersion: v1
kind: Pod
metadata:
  name: quota-pod
  namespace: trainxops
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep infinity"]
    resources:
      requests:
        cpu: "3" # This exceeds the requests.cpu quota of "2"
        memory: "3Gi" # This exceeds the requests.memory quota of "2Gi"
      limits:
        cpu: "5" # This exceeds the limits.cpu quota of "4"
        memory: "5Gi" # This exceeds the limits.memory quota of "4Gi"