apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webserver-pod
  name: webserver-pod
spec:
  containers:
  - image: nginx
    name: webserver-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
